### PR TITLE
Allow to copy TensorMap

### LINKED ISSUE #98: copy function for tensor map
I think that would be just a simple helper function, because the copy function for tensor block already exists. So one needs to only create one loop. I am just not sure where this should be implemented. Python API or in the core?

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #98

### CODE REVIEW

**Review by agoscinski — COMMENTED** [review]
I did not really understand the unwind safety idea in Rust, and I feel like I need much more time to fully understand it, but shouldn't there be some test for eqs_tensormap_copy, when it fails returning a null ptr? So far I only see a test when it works

**Comment by Luthaf** [comment]
> shouldn't there be some test for eqs_tensormap_copy, when it fails returning a null ptr?

That's fair!

> I did not really understand the unwind safety idea in Rust

The core of it is when Rust code panics (or a C++ exception is thrown), the code starts unwinding the call stack until it reached a panic handler (`catch` block in C++), and while unwinding the code needs to clean up temporaries values and run their destructors.

This operation is only well defined within a single language, since e.g. Rust and C++ might have different semantics w.r.t. what happens during unwinding, so we need to catch panics/exceptions before handing back control to C in the C API implementation.

On top of that, a panic could leave a value in a half-initalized state, leading to hard to debug issues. So Rust does not allow to store data outside of a `catch_panic` call by the closure passed to `catch_panic`, unless this data is `UnwindSafe`, i.e. the data will always be valid. We can then use `std::panic::AssertUnwindSafe` to tell the compiler a given value is unwind safe, and write to it inside the `catch_panic` call.

**Comment by Luthaf** [comment]
It looks like we are hitting https://github.com/readthedocs/actions/issues/23 on the CI

**Review by agoscinski — APPROVED** [review]
Looks good

**Pull request merged**
