### PR TITLE
Run doctests and unittest-based tests with pytest

### PR DESCRIPTION
**Pull request by Luthaf**
The current hack to run doctests is starting to fail for some reason (see for example https://github.com/lab-cosmo/equistore/actions/runs/4374795802/jobs/7654672493), so let's move to pytest for this. 

This PR also uses pytest to run all unittest-based tests, so we only have to change the test syntax to finish #176

----
:books: Documentation preview :books:: https://equistore--182.org.readthedocs.build/en/182/

### CODE REVIEW

**Comment by Luthaf** [comment]
The failure of the current hack is is really weird: 

```
 ======================================================================
ERROR: test_doctests (doctests.TestDoctests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/equistore/equistore/python/tests/doctests.py", line 16, in test_doctests
    submodule = importlib.import_module("equistore." + module.name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'equistore.operations.equal_metadata'
```

The code was trying to all sub-module by looking at all files, and then importing them. Here it is trying to import `equistore/operations/equal_metadata.py`, which does not exists on master or other impacted branches!!! This file is added in #147, which is not merged yet. This makes no sense to me ...

**Comment by Luthaf** [comment]
OK, culprit it 54000b8ae0d5592b1efc25adba141cada05cb278. @jwa7 you pushed that to master =)

**Comment by Luthaf** [comment]
I've reverted this commit and added protection to the master branch, this should prevent such accidental pushes

**Comment by PicoCentauri** [comment]
Thanks for adding this!

**Pull request merged**
